services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Andressa@55
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'clinicar_polls_redis_data:/bitnami/redis/data'

volumes:
  polls_pg_data: {}
  clinicar_polls_redis_data: {} # <-- NOME CORRIGIDO PARA BATER COM O USADO ACIMA